name: CAD Gallery
on:
  workflow_dispatch:
  push:
    branches: [ master ]
permissions:
  contents: read
  pages: write
  id-token: write
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy.outputs.page_url }}
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - name: Build Gallery
        uses: schmiddim/freecad-action@v3
        with:
          send-ping: 'true'
      - uses: actions/configure-pages@v6
      - uses: actions/upload-pages-artifact@v5
        with:
          path: ./gallery
      - id: deploy
        uses: actions/deploy-pages@v5